# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolygonDrawing.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolygonDrawing(object):
    def setupUi(self, PolygonDrawing):
        PolygonDrawing.setObjectName("PolygonDrawing")
        PolygonDrawing.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PolygonDrawing)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_label = FrameLabel2(PolygonDrawing)
        self.frame_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label.sizePolicy().hasHeightForWidth())
        self.frame_label.setSizePolicy(sizePolicy)
        self.frame_label.setMouseTracking(True)
        self.frame_label.setAutoFillBackground(True)
        self.frame_label.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_label.setObjectName("frame_label")
        self.verticalLayout.addWidget(self.frame_label)
        self.info_label = QtWidgets.QLabel(PolygonDrawing)
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.buttonBox = QtWidgets.QDialogButtonBox(PolygonDrawing)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(PolygonDrawing)
        self.buttonBox.accepted.connect(PolygonDrawing.accept)
        self.buttonBox.rejected.connect(PolygonDrawing.reject)
        QtCore.QMetaObject.connectSlotsByName(PolygonDrawing)

    def retranslateUi(self, PolygonDrawing):
        _translate = QtCore.QCoreApplication.translate
        PolygonDrawing.setWindowTitle(_translate("PolygonDrawing", "Dialog"))

from FrameLabel import FrameLabel2